package main

import (
	"gopkg.in/urfave/cli.v1"
	"os"
)

var (
	appName = "brazilian-correios-service"
	version = "0.0.1"
)

func main() {
	app := cli.NewApp()
	app.Name = appName
	app.Version = version
	app.Copyright = "(c) 2017 - Ricardo Pinto"
	app.Usage = "Correios service is a small app to deal Brazilian Correios return requests and track of objects"
	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:   "listen, l",
			Value:  "0.0.0.0:8000",
			Usage:  "Address and port on which Correios Service will accept HTTP requests",
			EnvVar: "LISTEN",
		},
		cli.StringFlag{
			Name:   "log-folder, lf",
			Value:  "",
			Usage:  `Log folder path for access and application logging. Default "stdout"`,
			EnvVar: "LOG_FOLDER",
		},
		cli.StringFlag{
			Name:   "revision-file",
			Value:  "",
			Usage:  "Expose the revision file generated by build into url",
			EnvVar: "REVISION_FILE",
		},
		cli.StringFlag{
			Name:   "database-file",
			Value:  "",
			Usage:  "Database configuration used by Correios Service to connect to database",
			EnvVar: "DATABASE_FILE",
		},
		cli.StringFlag{
			Name:   "correios-file",
			Value:  "",
			Usage:  "Correios configuration used by Correios Service to connect to Correios",
			EnvVar: "CORREIOS_FILE",
		},
		cli.StringFlag{
			Name:   "swagger-file",
			Value:  "",
			Usage:  "Expose the swagger file",
			EnvVar: "SWAGGER_FILE",
		},
		cli.StringFlag{
			Name:   "ssl-cert",
			Value:  "",
			Usage:  "Define SSL certificate to accept HTTPS requests",
			EnvVar: "SSL_CERT",
		},
		cli.StringFlag{
			Name:   "ssl-key",
			Value:  "",
			Usage:  "Define SSL key to accept HTTPS requests",
			EnvVar: "SSL_KEY",
		},
	}

	app.Action = Handle

	app.Run(os.Args)
}
